import { test, expect } from '../../../../fixtures/electron-online.fixture';

const MOCK_SERVER_PORT = 3456;

test.describe('CookieBusiness', () => {
  test('Set-Cookie 保存后续请求自动携带(含覆盖更新)', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie业务测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/override/old_value`);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/override/new_value`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('af_override=new_value', { timeout: 10000 });
    await expect(responseBody).not.toContainText('af_override=old_value', { timeout: 10000 });
  });

  test('Path 匹配：仅在匹配路径下携带 Cookie', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie Path 匹配测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/path`);
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/path-only/1`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('af_path=path_value', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/other`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await expect(responseBody).not.toContainText('af_path=path_value', { timeout: 10000 });
  });

  test('手动 Cookie 请求头完全覆盖自动注入', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie 手动覆盖测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/basic`);
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const headersTab = contentPage.locator('[data-testid="http-params-tab-headers"]');
    await headersTab.click();
    await contentPage.waitForTimeout(300);
    const headerKeyAutocomplete = contentPage.getByTestId('params-tree-key-autocomplete');
    const headerKeyInputs = contentPage.getByTestId('params-tree-key-input');
    const headerValueInputs = contentPage.getByTestId('params-tree-value-input');
    const headerKeyAutocompleteCount = await headerKeyAutocomplete.count();
    if (headerKeyAutocompleteCount > 0) {
      await headerKeyAutocomplete.first().locator('input').fill('Cookie');
    } else {
      await headerKeyInputs.first().fill('Cookie');
    }
    await headerValueInputs.first().click();
    await contentPage.keyboard.type('manual_cookie=1');
    await contentPage.waitForTimeout(300);
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('manual_cookie=1', { timeout: 10000 });
    await expect(responseBody).not.toContainText('af_basic=basic_value', { timeout: 10000 });
  });

  test('跨 host 不携带 Cookie', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie 跨 host 测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/basic`);
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://[::1]:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).not.toContainText('af_basic=basic_value', { timeout: 10000 });
  });

  test('Domain 属性不匹配时忽略 Cookie', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie Domain 不匹配测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/domain-mismatch`);
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).not.toContainText('af_domain_mismatch=1', { timeout: 10000 });
  });

  test('Max-Age=0 删除 Cookie', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie 删除测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    const responseArea = contentPage.getByTestId('response-area');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/basic`);
    await sendBtn.click();
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('af_basic=basic_value', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/delete-basic`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await expect(responseBody).not.toContainText('af_basic=basic_value', { timeout: 10000 });
  });

  test('同名不同 Path 发送顺序：更长 Path 在前', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie Path 顺序测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    const responseArea = contentPage.getByTestId('response-area');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/set-cookie/order`);
    await sendBtn.click();
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/path-only/1`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('af_order=long; af_order=short', { timeout: 10000 });
  });

  test('默认 Path：未设置 Path 使用目录', async ({ contentPage, clearCache, createProject, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('[data-testid="banner-add-http-btn"]');
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Cookie 默认 Path 测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    const responseArea = contentPage.getByTestId('response-area');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/set-cookie/default-path/dir/leaf`);
    await sendBtn.click();
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/set-cookie/default-path/dir/next`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toContainText('af_default_path=1', { timeout: 10000 });
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo/set-cookie/default-path/other`);
    await sendBtn.click();
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    await expect(responseBody).not.toContainText('af_default_path=1', { timeout: 10000 });
  });
});

