import { test, expect } from '../../../../../../fixtures/electron-online.fixture';

test.describe('CutNode', () => {
  test.describe('剪切HTTP节点', () => {
    test('剪切单个httpNode节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP节点' });
      await expect(sourceNode).toBeVisible({ timeout: 5000 });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await expect(cutItem).toBeVisible();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNode = contentPage.locator('.custom-tree-node.cut-node').filter({ hasText: '源HTTP节点' });
      await expect(cutNode).toBeVisible({ timeout: 3000 });
      await treeWrap.click({ button: 'right', position: { x: 100, y: 300 } });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await expect(pasteItem).toBeVisible();
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP节点' });
      await expect(allNodes).toHaveCount(1, { timeout: 5000 });
      const cutNodeAfterPaste = contentPage.locator('.custom-tree-node.cut-node');
      await expect(cutNodeAfterPaste).toHaveCount(0);
    });
    test('剪切单个httpNode节点粘贴到folder节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      await expect(folderDialog).toBeVisible({ timeout: 5000 });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP节点' });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await expect(pasteItem).toBeVisible();
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: '目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
      const childNode = expandedFolder.locator('.el-tree-node__content').filter({ hasText: '源HTTP节点' });
      await expect(childNode).toBeVisible({ timeout: 5000 });
      const rootNodes = contentPage.locator('.tree-wrap > .el-tree > .el-tree-node > .el-tree-node__content').filter({ hasText: '源HTTP节点' });
      await expect(rootNodes).toHaveCount(0);
    });
    test('剪切多个httpNode节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        await expect(addFileDialog).toBeVisible({ timeout: 5000 });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`HTTP节点${i}`);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const node1 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点1' });
      await node1.click();
      await contentPage.waitForTimeout(200);
      await contentPage.keyboard.down('Control');
      const node2 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点2' });
      await node2.click();
      await contentPage.waitForTimeout(200);
      const node3 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点3' });
      await node3.click();
      await contentPage.keyboard.up('Control');
      await contentPage.waitForTimeout(300);
      await node1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchCutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /批量剪切/ });
      await expect(batchCutItem).toBeVisible();
      await batchCutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNodes = contentPage.locator('.custom-tree-node.cut-node');
      await expect(cutNodes).toHaveCount(3);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: '目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
      const allNode1 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点1' });
      const allNode2 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点2' });
      const allNode3 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点3' });
      await expect(allNode1).toHaveCount(1, { timeout: 5000 });
      await expect(allNode2).toHaveCount(1, { timeout: 5000 });
      await expect(allNode3).toHaveCount(1, { timeout: 5000 });
    });
    test('剪切httpNode节点在非folder节点右键不显示粘贴选项', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 2; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`HTTP节点${i}`);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const node1 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点1' });
      await node1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const node2 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点2' });
      await node2.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await expect(pasteItem).toBeHidden();
    });
  });
  test.describe('剪切WebSocket节点', () => {
    test('剪切单个websocketNode节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源WebSocket节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WebSocket节点' });
      await expect(sourceNode).toBeVisible({ timeout: 5000 });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNode = contentPage.locator('.custom-tree-node.cut-node').filter({ hasText: '源WebSocket节点' });
      await expect(cutNode).toBeVisible({ timeout: 3000 });
      await treeWrap.click({ button: 'right', position: { x: 100, y: 300 } });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WebSocket节点' });
      await expect(allNodes).toHaveCount(1, { timeout: 5000 });
    });
    test('剪切单个websocketNode节点粘贴到folder节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('WS目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源WebSocket节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WebSocket节点' });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'WS目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: 'WS目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('剪切HTTP Mock节点', () => {
    test('剪切单个httpMockNode节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源HTTP Mock节点');
      const mockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' });
      await mockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP Mock节点' });
      await expect(sourceNode).toBeVisible({ timeout: 5000 });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 300 } });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP Mock节点' });
      await expect(allNodes).toHaveCount(1, { timeout: 5000 });
    });
    test('剪切单个httpMockNode节点粘贴到folder节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('Mock目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源HTTP Mock节点');
      const mockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' });
      await mockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源HTTP Mock节点' });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'Mock目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: 'Mock目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('剪切WebSocket Mock节点', () => {
    test('剪切单个websocketMockNode节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源WS Mock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' });
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WS Mock节点' });
      await expect(sourceNode).toBeVisible({ timeout: 5000 });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 300 } });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WS Mock节点' });
      await expect(allNodes).toHaveCount(1, { timeout: 5000 });
    });
    test('剪切单个websocketMockNode节点粘贴到folder节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('WSMock目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('源WS Mock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' });
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '源WS Mock节点' });
      await sourceNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'WSMock目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTime
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: 'WSMock目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('剪切文件夹节点', () => {
    test('剪切单个folder节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('源文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceFolder = contentPage.locator('.el-tree-node__content').filter({ hasText: '源文件夹' });
      await expect(sourceFolder).toBeVisible({ timeout: 5000 });
      await sourceFolder.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNode = contentPage.locator('.custom-tree-node.cut-node').filter({ hasText: '源文件夹' });
      await expect(cutNode).toBeVisible({ timeout: 3000 });
      await treeWrap.click({ button: 'right', position: { x: 100, y: 300 } });
      await contentPage.waitForTime
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allFolders = contentPage.locator('.el-tree-node__content').filter({ hasText: '源文件夹' });
      await expect(allFolders).toHaveCount(1, { timeout: 5000 });
    });
    test('剪切包含子节点的folder节点', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('父文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const parentFolder = contentPage.locator('.custom-tree-node').filter({ hasText: '父文件夹' });
      await parentFolder.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('子节点HTTP');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem2 = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem2.click();
      await contentPage.waitForTimeout(300);
      const folderDialog2 = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput2 = folderDialog2.locator('input').first();
      await folderNameInput2.fill('目标文件夹');
      const folderConfirmBtn2 = folderDialog2.locator('.el-button--primary').last();
      await folderConfirmBtn2.click();
      await contentPage.waitForTimeout(500);
      await parentFolder.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const targetFolder = contentPage.locator('.custom-tree-node').filter({ hasText: '目标文件夹' });
      await targetFolder.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedTargetFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: '目标文件夹' });
      await expect(expandedTargetFolder).toBeVisible({ timeout: 5000 });
      const childFolder = expandedTargetFolder.locator('.custom-tree-node').filter({ hasText: '父文件夹' });
      await expect(childFolder).toBeVisible({ timeout: 5000 });
      const childFolderContent = childFolder.locator('xpath=ancestor::div[contains(@class,"el-tree-node__content")]');
      const folderExpander = childF.first();
      await folderExpander.click({ timeout: 5000 });
      await contentPage.waitForTimeout(300);
      const childHttpNode = contentPage.locator('.custom-tree-node').filter({ hasText: '子节点HTTP' });
      await expect(childHttpNode).toHaveCount(1, { timeout: 5000 });
    });
  });
  test.describe('剪切混合节点', () => {
    test('批量剪切不同类型节点粘贴到根节点下', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      let newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      let addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      let nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合HTTP节点');
      let confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合WebSocket节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '混合HTTP节点' });
      await httpNode.click();
      await contentPage.waitForTimeout(200);
      await contentPage.keyboard.down('Control');
      const wsNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '混合WebSocket节点' });
      await wsNode.click();
      await contentPage.keyboard.up('Control');
      await contentPage.waitForTimeout(300);
      await httpNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchCutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /批量剪切/ });
      await batchCutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNodes = contentPage.locator('.custom-tree-node.cut-node');
      await expect(cutNodes).toHaveCount(2);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '目标文件夹' });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: '目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
      const allHttpNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '混合HTTP节点' });
      const allWsNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '混合WebSocket节点' });
      await expect(allHttpNodes).toHaveCount(1, { timeout: 5000 });
      await expect(allWsNodes).toHaveCount(1, { timeout: 5000 });
    });
  });
  test.describe('快捷键剪切粘贴', () => {
    test('使用Ctrl+X和Ctrl+V剪切粘贴节点', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('快捷键测试节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const newFolderItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('目标文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const sourceNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '快捷键测试节点' });
      await sourceNode.click();
      await contentPage.waitForTimeout(200);
      await contentPage.keyboard.press('Control+x');
      await contentPage.waitForTimeout(300);
      const cutNode = contentPage.locator('.custom-tree-node.cut-node').filter({ hasText: '快捷键测试节点' });
      await expect(cutNode).toBeVisible({ timeout: 3000 });
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '目标文件夹' });
      await folderNode.click();
      await contentPage.waitForTime
      await contentPage.keyboard.press('Control+v');
      await contentPage.waitForTimeout(500);
      const expandedFolder = contentPage.locator('.el-tree-node.is-expanded').filter({ hasText: '目标文件夹' });
      await expect(expandedFolder).toBeVisible({ timeout: 5000 });
      const allNodes = contentPage.locator('.el-tree-node__content').filter({ hasText: '快捷键测试节点' });
      await expect(allNodes).toHaveCount(1, { timeout: 5000 });
    });
  });
  test.describe('剪切特殊情况', () => {
    test('剪切节点后进行复制操作,原剪切内容被覆盖', async ({ contentPage, clearCache, createProject, loginAccount }) => {
      await clearCache();

      await loginAccount();
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 2; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const newInterfaceItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`HTTP节点${i}`);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const node1 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点1' });
      await node1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const cutItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /剪切/ }).first();
      await cutItem.click();
      await contentPage.waitForTimeout(300);
      const cutNode = contentPage.locator('.custom-tree-node.cut-node').filter({ hasText: 'HTTP节点1' });
      await expect(cutNode).toBeVisible({ timeout: 3000 });
      const node2 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点2' });
      await node2.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const copyItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /复制/ }).first();
      await copyItem.click();
      await contentPage.waitForTimeout(300);
      const cutNodeAfterCopy = contentPage.locator('.custom-tree-node.cut-node');
      await expect(cutNodeAfterCopy).toHaveCount(0);
      await treeWrap.click({ button: 'right', position: { x: 100, y: 400 } });
      await contentPage.waitForTimeout(300);
      const pasteItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /粘贴/ });
      await pasteItem.click();
      await contentPage.waitForTimeout(500);
      const allNode1 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点1' });
      const allNode2 = contentPage.locator('.el-tree-node__content').filter({ hasText: 'HTTP节点2' });
      await expect(allNode1).toHaveCount(1, { timeout: 5000 });
      await expect(allNode2).toHaveCount(2, { timeout: 5000 });
    });
  });
});
