import { test, expect } from '../../../../../../../fixtures/electron-online.fixture';

const MOCK_SERVER_PORT = 3456;

test.describe('AfHttpApi', () => {
  // 使用af.http.get发送GET请求并把返回结果写入主请求头
  test('使用af.http.get发送GET请求并获取响应数据', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.http.get测试' });
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `const response = await af.http.get("http://127.0.0.1:${MOCK_SERVER_PORT}/echo?test=preGet");
af.request.headers["X-Pre-Get-Status"] = String(response.statusCode);
af.request.headers["X-Pre-Get-Method"] = String((response.json && response.json.method) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.locator('.s-json-editor').first();
    await expect(responseBody).toContainText('x-pre-get-status', { timeout: 10000 });
    await expect(responseBody).toContainText('200', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-get-method', { timeout: 10000 });
    await expect(responseBody).toContainText('GET', { timeout: 10000 });
  });
  // 使用af.http.post发送POST请求并把返回结果写入主请求头
  test('使用af.http.post发送POST请求并获取响应数据', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.http.post测试' });
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `const response = await af.http.post("http://127.0.0.1:${MOCK_SERVER_PORT}/echo");
af.request.headers["X-Pre-Post-Status"] = String(response.statusCode);
af.request.headers["X-Pre-Post-Method"] = String((response.json && response.json.method) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.locator('.s-json-editor').first();
    await expect(responseBody).toContainText('x-pre-post-status', { timeout: 10000 });
    await expect(responseBody).toContainText('200', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-post-method', { timeout: 10000 });
    await expect(responseBody).toContainText('POST', { timeout: 10000 });
  });
  // 使用af.http.put发送PUT请求并把返回结果写入主请求头
  test('使用af.http.put发送PUT请求并获取响应数据', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.http.put测试' });
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `const response = await af.http.put("http://127.0.0.1:${MOCK_SERVER_PORT}/echo");
af.request.headers["X-Pre-Put-Status"] = String(response.statusCode);
af.request.headers["X-Pre-Put-Method"] = String((response.json && response.json.method) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.locator('.s-json-editor').first();
    await expect(responseBody).toContainText('x-pre-put-status', { timeout: 10000 });
    await expect(responseBody).toContainText('200', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-put-method', { timeout: 10000 });
    await expect(responseBody).toContainText('PUT', { timeout: 10000 });
  });
  // 使用af.http.delete发送DELETE请求并把返回结果写入主请求头
  test('使用af.http.delete发送DELETE请求并获取响应数据', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.http.delete测试' });
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `const response = await af.http.delete("http://127.0.0.1:${MOCK_SERVER_PORT}/echo?id=123");
af.request.headers["X-Pre-Delete-Status"] = String(response.statusCode);
af.request.headers["X-Pre-Delete-Method"] = String((response.json && response.json.method) || "");
af.request.headers["X-Pre-Delete-Id"] = String((response.json && response.json.query && response.json.query.id) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.locator('.s-json-editor').first();
    await expect(responseBody).toContainText('x-pre-delete-status', { timeout: 10000 });
    await expect(responseBody).toContainText('200', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-delete-method', { timeout: 10000 });
    await expect(responseBody).toContainText('DELETE', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-delete-id', { timeout: 10000 });
    await expect(responseBody).toContainText('123', { timeout: 10000 });
  });
  // af.http请求失败时在脚本catch分支可拿到错误并继续主请求
  test('af.http请求失败时正确抛出错误', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.http错误处理测试' });
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `const errorState = await af.http.get("http://127.0.0.1:59999/invalid-endpoint").then(() => "no-message").catch((error) => (error && error.message ? "has-message" : "no-message"));
af.request.headers["X-Pre-Http-Error"] = "captured";
af.request.headers["X-Pre-Http-Error-Message"] = errorState;`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseArea = contentPage.getByTestId('response-area');
    await expect(responseArea).toBeVisible({ timeout: 10000 });
    await expect(responseArea.getByTestId('status-code')).toContainText('200', { timeout: 10000 });
    const responseBody = responseArea.locator('.s-json-editor').first();
    await expect(responseBody).toContainText('x-pre-http-error', { timeout: 10000 });
    await expect(responseBody).toContainText('captured', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-http-error-message', { timeout: 10000 });
    await expect(responseBody).toContainText('has-message', { timeout: 10000 });
  });
});
