import { test, expect } from '../../../../../../../fixtures/electron-online.fixture';

const MOCK_SERVER_PORT = 3456;

test.describe('EnvVariableAccess', () => {
  // 使用af.envs读取变量并写入请求头
  test('使用af.envs获取所有环境变量列表', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.envs测试' });
    const variableBtn = contentPage.locator('[data-testid="http-params-variable-btn"]').first();
    await variableBtn.click();
    await contentPage.waitForTimeout(300);
    const variableTab = contentPage.locator('[data-testid="project-nav-tab-variable"]');
    await expect(variableTab).toHaveClass(/active/, { timeout: 5000 });
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const addPanel = variablePage.locator('.left');
    const nameFormItem = addPanel.locator('.el-form-item').filter({ hasText: /变量名称|Variable Name|Name/ });
    await nameFormItem.locator('input').first().fill('testEnvVar');
    const valueFormItem = addPanel.locator('.el-form-item').filter({ hasText: /变量值|Value/ });
    await valueFormItem.locator('textarea').first().fill('test_value');
    const confirmAddBtn = addPanel.locator('.el-button--primary').filter({ hasText: /确认添加|Add|Confirm/ }).first();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    await expect(variablePage.locator('.right')).toContainText('testEnvVar', { timeout: 5000 });
    await nameFormItem.locator('input').first().fill('anotherVar');
    await valueFormItem.locator('textarea').first().fill('another_value');
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    await expect(variablePage.locator('.right')).toContainText('anotherVar', { timeout: 5000 });
    const httpTab = contentPage.locator('.nav .item').filter({ hasText: 'af.envs测试' }).first();
    await httpTab.click();
    await contentPage.waitForTimeout(3000);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `af.request.headers["X-Pre-Envs-TestEnvVar"] = String((af.envs && af.envs.testEnvVar) || "");
af.request.headers["X-Pre-Envs-AnotherVar"] = String((af.envs && af.envs.anotherVar) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseBody = contentPage.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toBeVisible({ timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-envs-testenvvar', { timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-envs-anothervar', { timeout: 10000 });
  });
  // 使用af.currentEnv读取变量并写入请求头
  test('使用af.currentEnv获取当前激活的环境变量', async ({ contentPage, clearCache, createProject, createNode, loginAccount }) => {
    await clearCache();
    await loginAccount();
    await createProject();
    await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
    await createNode(contentPage, { nodeType: 'http', name: 'af.currentEnv测试' });
    const variableBtn = contentPage.locator('[data-testid="http-params-variable-btn"]').first();
    await variableBtn.click();
    await contentPage.waitForTimeout(300);
    const variableTab = contentPage.locator('[data-testid="project-nav-tab-variable"]');
    await expect(variableTab).toHaveClass(/active/, { timeout: 5000 });
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const addPanel = variablePage.locator('.left');
    const nameFormItem = addPanel.locator('.el-form-item').filter({ hasText: /变量名称|Variable Name|Name/ });
    await nameFormItem.locator('input').first().fill('currentEnvVar');
    const valueFormItem = addPanel.locator('.el-form-item').filter({ hasText: /变量值|Value/ });
    await valueFormItem.locator('textarea').first().fill('current_value');
    const confirmAddBtn = addPanel.locator('.el-button--primary').filter({ hasText: /确认添加|Add|Confirm/ }).first();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    await expect(variablePage.locator('.right')).toContainText('currentEnvVar', { timeout: 5000 });
    const httpTab = contentPage.locator('.nav .item').filter({ hasText: 'af.currentEnv测试' }).first();
    await httpTab.click();
    await contentPage.waitForTimeout(3000);
    const urlInput = contentPage.locator('[data-testid="url-input"] [contenteditable]');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const preScriptTab = contentPage.locator('[data-testid="http-params-tab-prescript"]');
    await preScriptTab.click();
    await contentPage.waitForTimeout(500);
    const editor = contentPage.locator('.s-monaco-editor');
    await expect(editor).toBeVisible({ timeout: 5000 });
    await editor.click();
    await contentPage.waitForTimeout(300);
    const scriptCode = `af.request.headers["X-Pre-CurrentEnv-Var"] = String((af.currentEnv && af.currentEnv.currentEnvVar) || "");`;
    await contentPage.keyboard.type(scriptCode);
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('[data-testid="operation-send-btn"]');
    await sendBtn.click();
    const responseBody = contentPage.getByTestId('response-tab-body').locator('.s-json-editor').first();
    await expect(responseBody).toBeVisible({ timeout: 10000 });
    await expect(responseBody).toContainText('x-pre-currentenv-var', { timeout: 10000 });
  });
});
