import { test, expect } from '../../../../../../fixtures/electron.fixture';

test.describe('DeleteNode', () => {
  test.describe('删除httpNode节点', () => {
    test('鼠标右键httpNode节点删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HTTP节点' });
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const confirmMessage = confirmDialog.locator('.el-message-box__message');
      await expect(confirmMessage).toContainText('待删除HTTP节点');
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HTTP节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('鼠标移动到httpNode节点,点击更多操作删除节点', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HTTP节点' });
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = httpNode.locator('.more-btn');
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HTTP节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('按住ctrl鼠标左键批量选择httpNode节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const contextMenu = contentPage.locator('.s-contextmenu');
        const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        await expect(addFileDialog).toBeVisible({ timeout: 5000 });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`批量删除HTTP节点${i}`);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const httpNode1 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除HTTP节点1' });
      const httpNode2 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除HTTP节点2' });
      const httpNode3 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除HTTP节点3' });
      await httpNode1.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await httpNode2.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await httpNode3.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(httpNode1).toHaveClass(/select-node/);
      await expect(httpNode2).toHaveClass(/select-node/);
      await expect(httpNode3).toHaveClass(/select-node/);
      await httpNode1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await expect(httpNode1).toBeHidden({ timeout: 5000 });
      await expect(httpNode2).toBeHidden({ timeout: 5000 });
      await expect(httpNode3).toBeHidden({ timeout: 5000 });
    });
  });
  test.describe('删除websocketNode节点', () => {
    test('鼠标右键websocketNode节点删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除Websocket节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const websocketOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket/ });
      await websocketOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const websocketNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除Websocket节点' });
      await expect(websocketNode).toBeVisible({ timeout: 5000 });
      await websocketNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const confirmMessage = confirmDialog.locator('.el-message-box__message');
      await expect(confirmMessage).toContainText('待删除Websocket节点');
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除Websocket节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('鼠标移动到websocketNode节点,点击更多操作删除节点', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除Websocket节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const websocketOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket/ });
      await websocketOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const websocketNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除Websocket节点' });
      await expect(websocketNode).toBeVisible({ timeout: 5000 });
      await websocketNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = websocketNode.locator('.more-btn');
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除Websocket节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('按住ctrl鼠标左键批量选择websocketNode节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const contextMenu = contentPage.locator('.s-contextmenu');
        const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        await expect(addFileDialog).toBeVisible({ timeout: 5000 });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`批量删除WS节点${i}`);
        const typeSelect = addFileDialog.locator('.el-select').first();
        await typeSelect.click();
        await contentPage.waitForTimeout(200);
        const websocketOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket/ });
        await websocketOption.click();
        await contentPage.waitForTimeout(200);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const wsNode1 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WS节点1' });
      const wsNode2 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WS节点2' });
      const wsNode3 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WS节点3' });
      await wsNode1.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsNode2.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsNode3.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(wsNode1).toHaveClass(/select-node/);
      await expect(wsNode2).toHaveClass(/select-node/);
      await expect(wsNode3).toHaveClass(/select-node/);
      await wsNode1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await expect(wsNode1).toBeHidden({ timeout: 5000 });
      await expect(wsNode2).toBeHidden({ timeout: 5000 });
      await expect(wsNode3).toBeHidden({ timeout: 5000 });
    });
  });
  test.describe('删除httpMockNode节点', () => {
    test('鼠标右键httpMockNode节点删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除HttpMock节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const httpMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /HTTP Mock/ });
      await httpMockOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HttpMock节点' });
      await expect(httpMockNode).toBeVisible({ timeout: 5000 });
      await httpMockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const confirmMessage = confirmDialog.locator('.el-message-box__message');
      await expect(confirmMessage).toContainText('待删除HttpMock节点');
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HttpMock节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('鼠标移动到httpMockNode节点,点击更多操作删除节点', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除HttpMock节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const httpMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /HTTP Mock/ });
      await httpMockOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HttpMock节点' });
      await expect(httpMockNode).toBeVisible({ timeout: 5000 });
      await httpMockNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = httpMockNode.locator('.more-btn');
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除HttpMock节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('按住ctrl鼠标左键批量选择httpMockNode节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const contextMenu = contentPage.locator('.s-contextmenu');
        const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        await expect(addFileDialog).toBeVisible({ timeout: 5000 });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`批量删除Mock节点${i}`);
        const typeSelect = addFileDialog.locator('.el-select').first();
        await typeSelect.click();
        await contentPage.waitForTimeout(200);
        const httpMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /HTTP Mock/ });
        await httpMockOption.click();
        await contentPage.waitForTimeout(200);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const mockNode1 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除Mock节点1' });
      const mockNode2 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除Mock节点2' });
      const mockNode3 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除Mock节点3' });
      await mockNode1.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await mockNode2.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await mockNode3.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(mockNode1).toHaveClass(/select-node/);
      await expect(mockNode2).toHaveClass(/select-node/);
      await expect(mockNode3).toHaveClass(/select-node/);
      await mockNode1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await expect(mockNode1).toBeHidden({ timeout: 5000 });
      await expect(mockNode2).toBeHidden({ timeout: 5000 });
      await expect(mockNode3).toBeHidden({ timeout: 5000 });
    });
  });
  test.describe('删除websocketMockNode节点', () => {
    test('鼠标右键websocketMockNode节点删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除WsMock节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const wsMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket Mock/ });
      await wsMockOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除WsMock节点' });
      await expect(wsMockNode).toBeVisible({ timeout: 5000 });
      await wsMockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const confirmMessage = confirmDialog.locator('.el-message-box__message');
      await expect(confirmMessage).toContainText('待删除WsMock节点');
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除WsMock节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('鼠标移动到websocketMockNode节点,点击更多操作删除节点', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待删除WsMock节点');
      const typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const wsMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket Mock/ });
      await wsMockOption.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除WsMock节点' });
      await expect(wsMockNode).toBeVisible({ timeout: 5000 });
      await wsMockNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = wsMockNode.locator('.more-btn');
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除WsMock节点' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('按住ctrl鼠标左键批量选择websocketMockNode节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const contextMenu = contentPage.locator('.s-contextmenu');
        const newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
        await newInterfaceItem.click();
        await contentPage.waitForTimeout(300);
        const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
        await expect(addFileDialog).toBeVisible({ timeout: 5000 });
        const nameInput = addFileDialog.locator('input').first();
        await nameInput.fill(`批量删除WsMock${i}`);
        const typeSelect = addFileDialog.locator('.el-select').first();
        await typeSelect.click();
        await contentPage.waitForTimeout(200);
        const wsMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket Mock/ });
        await wsMockOption.click();
        await contentPage.waitForTimeout(200);
        const confirmBtn = addFileDialog.locator('.el-button--primary').last();
        await confirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const wsMockNode1 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WsMock1' });
      const wsMockNode2 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WsMock2' });
      const wsMockNode3 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除WsMock3' });
      await wsMockNode1.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsMockNode2.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsMockNode3.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(wsMockNode1).toHaveClass(/select-node/);
      await expect(wsMockNode2).toHaveClass(/select-node/);
      await expect(wsMockNode3).toHaveClass(/select-node/);
      await wsMockNode1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await expect(wsMockNode1).toBeHidden({ timeout: 5000 });
      await expect(wsMockNode2).toBeHidden({ timeout: 5000 });
      await expect(wsMockNode3).toBeHidden({ timeout: 5000 });
    });
  });
  test.describe('删除folder节点', () => {
    test('鼠标右键folder节点删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      await expect(folderDialog).toBeVisible({ timeout: 5000 });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('待删除文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const confirmMessage = confirmDialog.locator('.el-message-box__message');
      await expect(confirmMessage).toContainText('待删除文件夹');
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除文件夹' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('鼠标移动到folder节点,点击更多操作删除节点', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      await expect(folderDialog).toBeVisible({ timeout: 5000 });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('待删除文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = folderNode.locator('.more-btn');
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const deleteItem = contentPage.locator('.s-contextmenu .contextmenu-item', { hasText: /删除/ });
      await expect(deleteItem).toBeVisible();
      await deleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      const deletedNode = contentPage.locator('.el-tree-node').filter({ hasText: '待删除文件夹' });
      await expect(deletedNode).toBeHidden({ timeout: 5000 });
    });
    test('按住ctrl鼠标左键批量选择folder节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      for (let i = 1; i <= 3; i++) {
        await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
        await contentPage.waitForTimeout(300);
        const contextMenu = contentPage.locator('.s-contextmenu');
        const newFolderItem = contextMenu.locator('.contextmenu-item', { hasText: /新建文件夹/ });
        await newFolderItem.click();
        await contentPage.waitForTimeout(300);
        const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
        await expect(folderDialog).toBeVisible({ timeout: 5000 });
        const folderNameInput = folderDialog.locator('input').first();
        await folderNameInput.fill(`批量删除文件夹${i}`);
        const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
        await folderConfirmBtn.click();
        await contentPage.waitForTimeout(500);
      }
      const folderNode1 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除文件夹1' });
      const folderNode2 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除文件夹2' });
      const folderNode3 = contentPage.locator('.el-tree-node').filter({ hasText: '批量删除文件夹3' });
      await folderNode1.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await folderNode2.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await folderNode3.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(folderNode1).toHaveClass(/select-node/);
      await expect(folderNode2).toHaveClass(/select-node/);
      await expect(folderNode3).toHaveClass(/select-node/);
      await folderNode1.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      await expect(folderNode1).toBeHidden({ timeout: 5000 });
      await expect(folderNode2).toBeHidden({ timeout: 5000 });
      await expect(folderNode3).toBeHidden({ timeout: 5000 });
    });
  });
  test.describe('删除混合节点', () => {
    test('按住ctrl鼠标左键批量选择httpNode,websocketNode,httpMockNode,websocketMockNode,folder节点,鼠标右键批量删除', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await contentPage.waitForURL(/.*#\/home.*/, { timeout: 5000 });
      await createProject();
      await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      // 创建httpNode
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      let contextMenu = contentPage.locator('.s-contextmenu');
      let newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      let addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      let nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合删除HTTP');
      let confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 创建websocketNode
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      contextMenu = contentPage.locator('.s-contextmenu');
      newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合删除WS');
      let typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      let wsOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket/ }).first();
      await wsOption.click();
      await contentPage.waitForTimeout(200);
      confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 创建httpMockNode
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      contextMenu = contentPage.locator('.s-contextmenu');
      newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合删除HttpMock');
      typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const httpMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /HTTP Mock/ });
      await httpMockOption.click();
      await contentPage.waitForTimeout(200);
      confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 创建websocketMockNode
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      contextMenu = contentPage.locator('.s-contextmenu');
      newInterfaceItem = contextMenu.locator('.contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建接口/ });
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('混合删除WsMock');
      typeSelect = addFileDialog.locator('.el-select').first();
      await typeSelect.click();
      await contentPage.waitForTimeout(200);
      const wsMockOption = contentPage.locator('.el-select-dropdown__item', { hasText: /WebSocket Mock/ });
      await wsMockOption.click();
      await contentPage.waitForTimeout(200);
      confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 创建folder
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const folderDialog = contentPage.locator('.el-dialog').filter({ hasText: /新建文件夹|新增文件夹/ });
      await expect(folderDialog).toBeVisible({ timeout: 5000 });
      const folderNameInput = folderDialog.locator('input').first();
      await folderNameInput.fill('混合删除文件夹');
      const folderConfirmBtn = folderDialog.locator('.el-button--primary').last();
      await folderConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 批量选择所有节点
      const httpNode = contentPage.locator('.el-tree-node').filter({ hasText: '混合删除HTTP' });
      const wsNode = contentPage.locator('.el-tree-node').filter({ hasText: '混合删除WS' });
      const httpMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '混合删除HttpMock' });
      const wsMockNode = contentPage.locator('.el-tree-node').filter({ hasText: '混合删除WsMock' });
      const folderNode = contentPage.locator('.el-tree-node').filter({ hasText: '混合删除文件夹' });
      await httpNode.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsNode.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await httpMockNode.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await wsMockNode.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(200);
      await folderNode.click({ modifiers: ['Control'] });
      await contentPage.waitForTimeout(300);
      await expect(httpNode).toHaveClass(/select-node/);
      await expect(wsNode).toHaveClass(/select-node/);
      await expect(httpMockNode).toHaveClass(/select-node/);
      await expect(wsMockNode).toHaveClass(/select-node/);
      await expect(folderNode).toHaveClass(/select-node/);
      // 右键批量删除
      await httpNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const batchMenu = contentPage.locator('.s-contextmenu');
      const batchDeleteItem = batchMenu.locator('.contextmenu-item', { hasText: /批量删除/ });
      await expect(batchDeleteItem).toBeVisible();
      await batchDeleteItem.click();
      await contentPage.waitForTimeout(300);
      const confirmDialog = contentPage.locator('.el-message-box');
      await expect(confirmDialog).toBeVisible({ timeout: 5000 });
      const dialogConfirmBtn = confirmDialog.locator('.el-button--primary');
      await dialogConfirmBtn.click();
      await contentPage.waitForTimeout(500);
      // 验证所有节点都被删除
      await expect(httpNode).toBeHidden({ timeout: 5000 });
      await expect(wsNode).toBeHidden({ timeout: 5000 });
      await expect(httpMockNode).toBeHidden({ timeout: 5000 });
      await expect(wsMockNode).toBeHidden({ timeout: 5000 });
      await expect(folderNode).toBeHidden({ timeout: 5000 });
    });
  });
});
