import { test, expect } from '../../../../../../fixtures/electron.fixture';

test.describe('RenameNode', () => {
  test.describe('重命名httpNode节点', () => {
    test('active节点,点击节点右键,点击重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待重命名HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名HTTP节点' });
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await expect(renameInput).toBeFocused();
      await renameInput.fill('新HTTP节点名称');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '新HTTP节点名称' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
      const oldNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名HTTP节点' });
      await expect(oldNode).toBeHidden({ timeout: 5000 });
    });
    test('active节点,F2重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待F2重命名HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.custom-tree-node').filter({ hasText: '待F2重命名HTTP节点' }).first();
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.click();
      await contentPage.waitForTimeout(300);
      await expect(httpNode).toHaveClass(/active-node/);
      await contentPage.keyboard.press('F2');
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await expect(renameInput).toBeFocused();
      await renameInput.fill('F2重命名后HTTP节点');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'F2重命名后HTTP节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('点击节点更多操作,点击重命名,输入名称,blur', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待更多操作重命名HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待更多操作重命名HTTP节点' });
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = httpNode.locator('.more').first();
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('更多操作重命名后HTTP节点');
      await treeWrap.click({ position: { x: 10, y: 10 } });
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '更多操作重命名后HTTP节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('节点名称未填写不允许重命名', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('空名称测试HTTP节点');
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const httpNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试HTTP节点' });
      await expect(httpNode).toBeVisible({ timeout: 5000 });
      await httpNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('');
      await contentPage.waitForTimeout(200);
      await expect(renameInput).toHaveClass(/error/);
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const originalNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试HTTP节点' });
      await expect(originalNode).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('重命名websocketNode节点', () => {
    test('active节点,点击节点右键,点击重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待重命名WS节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名WS节点' });
      await expect(wsNode).toBeVisible({ timeout: 5000 });
      await wsNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('新WS节点名称');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '新WS节点名称' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('active节点,F2重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待F2重命名WS节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待F2重命名WS节点' });
      await expect(wsNode).toBeVisible({ timeout: 5000 });
      await wsNode.click();
      await contentPage.waitForTimeout(300);
      await contentPage.keyboard.press('F2');
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('F2重命名后WS节点');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'F2重命名后WS节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('点击节点更多操作,点击重命名,输入名称,blur', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待更多操作重命名WS节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待更多操作重命名WS节点' });
      await expect(wsNode).toBeVisible({ timeout: 5000 });
      await wsNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = wsNode.locator('.more').first();
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('更多操作重命名后WS节点');
      await treeWrap.click({ position: { x: 10, y: 10 } });
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '更多操作重命名后WS节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('节点名称未填写不允许重命名', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('空名称测试WS节点');
      const wsRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket' }).first();
      await wsRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const wsNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试WS节点' });
      await expect(wsNode).toBeVisible({ timeout: 5000 });
      await wsNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('');
      await contentPage.waitForTimeout(200);
      await expect(renameInput).toHaveClass(/error/);
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const originalNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试WS节点' });
      await expect(originalNode).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('重命名httpMockNode节点', () => {
    test('active节点,点击节点右键,点击重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待重命名HttpMock节点');
      const httpMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' }).first();
      await httpMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名HttpMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('新HttpMock节点名称');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '新HttpMock节点名称' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('active节点,F2重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待F2重命名HttpMock节点');
      const httpMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' }).first();
      await httpMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待F2重命名HttpMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click();
      await contentPage.waitForTimeout(300);
      await contentPage.keyboard.press('F2');
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('F2重命名后HttpMock节点');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'F2重命名后HttpMock节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('点击节点更多操作,点击重命名,输入名称,blur', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待更多操作重命名HttpMock节点');
      const httpMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' }).first();
      await httpMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待更多操作重命名HttpMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = mockNode.locator('.more').first();
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('更多操作重命名后HttpMock节点');
      await treeWrap.click({ position: { x: 10, y: 10 } });
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '更多操作重命名后HttpMock节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('节点名称未填写不允许重命名', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('空名称测试HttpMock节点');
      const httpMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'HTTP Mock' }).first();
      await httpMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试HttpMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('');
      await contentPage.waitForTimeout(200);
      await expect(renameInput).toHaveClass(/error/);
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const originalNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试HttpMock节点' });
      await expect(originalNode).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('重命名websocketMockNode节点', () => {
    test('active节点,点击节点右键,点击重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待重命名WsMock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' }).first();
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名WsMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('新WsMock节点名称');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '新WsMock节点名称' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('active节点,F2重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待F2重命名WsMock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' }).first();
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待F2重命名WsMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click();
      await contentPage.waitForTimeout(300);
      await contentPage.keyboard.press('F2');
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('F2重命名后WsMock节点');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'F2重命名后WsMock节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('点击节点更多操作,点击重命名,输入名称,blur', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('待更多操作重命名WsMock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' }).first();
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待更多操作重命名WsMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = mockNode.locator('.more').first();
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('更多操作重命名后WsMock节点');
      await treeWrap.click({ position: { x: 10, y: 10 } });
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '更多操作重命名后WsMock节点' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('节点名称未填写不允许重命名', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newInterfaceItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建接口/ });
      await newInterfaceItem.click();
      await contentPage.waitForTimeout(300);
      const addFileDialog = contentPage.locator('[data-testid="add-file-dialog"]');
      await expect(addFileDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFileDialog.locator('input').first();
      await nameInput.fill('空名称测试WsMock节点');
      const wsMockRadio = addFileDialog.locator('.el-radio').filter({ hasText: 'WebSocket Mock' }).first();
      await wsMockRadio.click();
      await contentPage.waitForTimeout(200);
      const confirmBtn = addFileDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const mockNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试WsMock节点' });
      await expect(mockNode).toBeVisible({ timeout: 5000 });
      await mockNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('');
      await contentPage.waitForTimeout(200);
      await expect(renameInput).toHaveClass(/error/);
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const originalNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试WsMock节点' });
      await expect(originalNode).toBeVisible({ timeout: 5000 });
    });
  });
  test.describe('重命名folder节点', () => {
    test('active节点,点击节点右键,点击重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const addFolderDialog = contentPage.locator('[data-testid="add-folder-dialog"]');
      await expect(addFolderDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFolderDialog.locator('input').first();
      await nameInput.fill('待重命名文件夹');
      const confirmBtn = addFolderDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待重命名文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await expect(renameItem).toBeVisible();
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('新文件夹名称');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '新文件夹名称' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('active节点,F2重命名,输入名称,回车', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const addFolderDialog = contentPage.locator('[data-testid="add-folder-dialog"]');
      await expect(addFolderDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFolderDialog.locator('input').first();
      await nameInput.fill('待F2重命名文件夹');
      const confirmBtn = addFolderDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待F2重命名文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.click();
      await contentPage.waitForTimeout(300);
      await contentPage.keyboard.press('F2');
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('F2重命名后文件夹');
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: 'F2重命名后文件夹' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('点击节点更多操作,点击重命名,输入名称,blur', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const addFolderDialog = contentPage.locator('[data-testid="add-folder-dialog"]');
      await expect(addFolderDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFolderDialog.locator('input').first();
      await nameInput.fill('待更多操作重命名文件夹');
      const confirmBtn = addFolderDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '待更多操作重命名文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.hover();
      await contentPage.waitForTimeout(300);
      const moreBtn = folderNode.locator('.more').first();
      await expect(moreBtn).toBeVisible({ timeout: 5000 });
      await moreBtn.click();
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('更多操作重命名后文件夹');
      await treeWrap.click({ position: { x: 10, y: 10 } });
      await contentPage.waitForTimeout(500);
      const renamedNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '更多操作重命名后文件夹' });
      await expect(renamedNode).toBeVisible({ timeout: 5000 });
    });
    test('节点名称未填写不允许重命名', async ({ contentPage, clearCache, createProject }) => {
      await clearCache();
      await createProject();
      await contentPage.waitForURL(/.*?#?\/workbench/, { timeout: 5000 });
      await contentPage.waitForTimeout(500);
      const treeWrap = contentPage.locator('.tree-wrap');
      await treeWrap.click({ button: 'right', position: { x: 100, y: 200 } });
      await contentPage.waitForTimeout(300);
      const contextMenu = contentPage.locator('.s-contextmenu');
      const newFolderItem = contextMenu.locator('.s-contextmenu-item', { hasText: /新建文件夹/ });
      await newFolderItem.click();
      await contentPage.waitForTimeout(300);
      const addFolderDialog = contentPage.locator('[data-testid="add-folder-dialog"]');
      await expect(addFolderDialog).toBeVisible({ timeout: 5000 });
      const nameInput = addFolderDialog.locator('input').first();
      await nameInput.fill('空名称测试文件夹');
      const confirmBtn = addFolderDialog.locator('.el-button--primary').last();
      await confirmBtn.click();
      await contentPage.waitForTimeout(500);
      const folderNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试文件夹' });
      await expect(folderNode).toBeVisible({ timeout: 5000 });
      await folderNode.click({ button: 'right' });
      await contentPage.waitForTimeout(300);
      const renameItem = contentPage.locator('.s-contextmenu .s-contextmenu-item', { hasText: /重命名/ });
      await renameItem.click();
      await contentPage.waitForTimeout(300);
      const renameInput = contentPage.locator('.tree-wrap .rename-ipt').first();
      await expect(renameInput).toBeVisible({ timeout: 5000 });
      await renameInput.fill('');
      await contentPage.waitForTimeout(200);
      await expect(renameInput).toHaveClass(/error/);
      await renameInput.press('Enter');
      await contentPage.waitForTimeout(500);
      const originalNode = contentPage.locator('.el-tree-node__content').filter({ hasText: '空名称测试文件夹' });
      await expect(originalNode).toBeVisible({ timeout: 5000 });
    });
  });
});

