import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'
import path from 'node:path'

test.describe('McpSourceContract', () => {
  test('主进程 MCP 服务保持本地固定端口和来源防护契约', async () => {
    const serviceSource = await fs.readFile(path.resolve('src/main/mcp/mcpService.ts'), 'utf8')
    expect(serviceSource).toContain("createServer((request, response) =>")
    expect(serviceSource).toContain('StreamableHTTPServerTransport')
    expect(serviceSource).toContain('sessionIdGenerator: undefined')
    expect(serviceSource).toContain('targetServer.listen(port, \'127.0.0.1\'')
    expect(serviceSource).toContain('return `http://127.0.0.1:${port}/mcp`')
    expect(serviceSource).toContain('requestUrl.pathname !== \'/mcp\'')
    expect(serviceSource).toContain('isAllowedHost(request)')
    expect(serviceSource).toContain('isAllowedOrigin(request)')
    expect(serviceSource).toContain("sendJson(response, 403, { error: 'Forbidden' })")
    expect(serviceSource).toContain("const code = message.includes('EADDRINUSE') ? 'PORT_IN_USE' : 'SERVER_START_FAILED'")
    expect(serviceSource).toContain('mcp:renderer:to:main:update-settings')
    expect(serviceSource).toContain('mcp:renderer:to:main:restart')
    expect(serviceSource).not.toContain('detect-port')
  })

  test('隐藏 executor 保持无 UI 常驻和 request-response IPC 契约', async () => {
    const executorSource = await fs.readFile(path.resolve('src/main/mcp/mcpExecutor.ts'), 'utf8')
    expect(executorSource).toContain('new BrowserWindow')
    expect(executorSource).toContain('show: false')
    expect(executorSource).toContain('skipTaskbar: true')
    expect(executorSource).toContain('app://mcp.html')
    expect(executorSource).toContain('http://localhost:4000/mcp.html')
    expect(executorSource).toContain('mcp:executor:to:main:ready')
    expect(executorSource).toContain('mcp:executor:to:main:response')
    expect(executorSource).toContain('EXECUTOR_NOT_READY')
    expect(executorSource).toContain('TOOL_TIMEOUT')
    expect(executorSource).toContain('unresponsive')
    expect(executorSource).toContain('render-process-gone')
    expect(executorSource).toContain('listMcpExecutorTools')
    expect(executorSource).toContain('callMcpExecutorTool')
    expect(executorSource).toContain('readMcpExecutorResource')
    const rendererSource = await fs.readFile(path.resolve('src/renderer/mcp.ts'), 'utf8')
    expect(rendererSource).toContain('mcp:main:to:executor:list-tools')
    expect(rendererSource).toContain('mcp:main:to:executor:call-tool')
    expect(rendererSource).toContain('mcp:main:to:executor:read-resource')
    expect(rendererSource).toContain('mcp:executor:to:main:ready')
    expect(rendererSource).not.toContain("from './main'")
  })

  test('MCP tool registry 只暴露核心离线工具并要求显式 projectId', async () => {
    const registrySource = await fs.readFile(path.resolve('src/renderer/mcp/toolRegistry.ts'), 'utf8')
    expect(registrySource).toContain("'getProjectList'")
    expect(registrySource).toContain("'createProject'")
    expect(registrySource).toContain("'createHttpNode'")
    expect(registrySource).toContain("'createWebsocketNode'")
    expect(registrySource).toContain("'createHttpMockNode'")
    expect(registrySource).toContain("'createWebsocketMockNode'")
    expect(registrySource).toContain("'getVariables'")
    expect(registrySource).toContain("'createGlobalCommonHeader'")
    expect(registrySource).toContain("'createFolder'")
    expect(registrySource).toContain("'moveNode'")
    expect(registrySource).toContain("'restoreNode'")
    expect(registrySource).toContain("runtimeStore.networkMode = 'offline'")
    expect(registrySource).toContain("required: ['projectId', ...tool.parameters.required]")
    expect(registrySource).toContain('prepareProjectContext(projectId)')
    expect(registrySource).toContain('TOOL_NOT_FOUND')
    expect(registrySource).toContain('INVALID_PARAMS')
    expect(registrySource).not.toContain("'navigateToProject'")
    expect(registrySource).not.toContain("'sendRequest'")
    expect(registrySource).not.toContain("'connectWebsocket'")
    expect(registrySource).not.toContain("'startHttpMockServer'")
    expect(registrySource).not.toContain('localStorage.setItem')
  })

  test('MCP resources 只读取 apiflow URI 且拒绝路径穿透', async () => {
    const resourceSource = await fs.readFile(path.resolve('src/renderer/mcp/resourceRegistry.ts'), 'utf8')
    expect(resourceSource).toContain("uri.startsWith('apiflow://')")
    expect(resourceSource).toContain("part === '..'")
    expect(resourceSource).toContain("part.includes('\\\\')")
    expect(resourceSource).toContain("part.includes('/')")
    expect(resourceSource).toContain("parsed.host === 'projects'")
    expect(resourceSource).toContain("parsed.host === 'nodes'")
    expect(resourceSource).toContain('projectCache.getProjectList()')
    expect(resourceSource).toContain('apiNodesCache.getApiNodesAsTree(projectId)')
    expect(resourceSource).toContain('nodeVariableCache.getVariableByProjectId(projectId)')
    expect(resourceSource).toContain('commonHeaderCache.getCommonHeaders()')
    expect(resourceSource).toContain('apiNodesCache.getNodeById(parts[0], true)')
    expect(resourceSource).toContain('INVALID_RESOURCE_URI')
    expect(resourceSource).toContain('RESOURCE_NOT_FOUND')
    expect(resourceSource).not.toContain('readFile')
  })

  test('设置页、preload 和构建入口暴露 MCP 管理入口', async () => {
    const settingsSource = await fs.readFile(path.resolve('src/renderer/pages/settings/Settings.vue'), 'utf8')
    const mcpSettingsSource = await fs.readFile(path.resolve('src/renderer/pages/settings/mcpSettings/McpSettings.vue'), 'utf8')
    const preloadSource = await fs.readFile(path.resolve('src/main/preload.ts'), 'utf8')
    const typeSource = await fs.readFile(path.resolve('src/types/main/index.ts'), 'utf8')
    const viteSource = await fs.readFile(path.resolve('vite.config.ts'), 'utf8')
    expect(settingsSource).toContain("action: 'mcp-settings'")
    expect(settingsSource).toContain('Cable')
    expect(await fs.readFile(path.resolve('src/main/main.ts'), 'utf8')).toContain('url.replace(/^(header|index|mcp)\\.html\\//')
    expect(mcpSettingsSource).toContain('window.electronAPI?.mcpManager.getStatus()')
    expect(mcpSettingsSource).toContain('window.electronAPI?.mcpManager.updateSettings')
    expect(mcpSettingsSource).toContain('window.electronAPI?.mcpManager.restart()')
    expect(mcpSettingsSource).toContain("t('MCP 服务')")
    expect(mcpSettingsSource).not.toContain('$t(')
    expect(preloadSource).toContain('mcpManager')
    expect(typeSource).toContain('mcpManager: {')
    expect(viteSource).toContain("mcp: resolve(__dirname, './mcp.html')")
  })
})
