import { test, expect } from '../../../fixtures/electron.fixture';

const MOCK_SERVER_PORT = 3456;

test.describe('Variable', () => {
  test('打开变量管理页面,显示新增变量表单和变量列表', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const addVariableForm = variablePage.locator('.left');
    await expect(addVariableForm).toBeVisible();
    const variableList = variablePage.locator('.right');
    await expect(variableList).toBeVisible();
  });

  test('新增string类型变量成功,变量列表中显示新增的变量', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('testString');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('hello world');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('testString');
    await expect(variableTable).toContainText('hello world');
    await expect(variableTable).toContainText('string');
  });

  test('新增number类型变量成功', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('testNumber');
    const typeSelect = variablePage.locator('.left .el-select');
    await typeSelect.click();
    const numberOption = contentPage.locator('.el-select-dropdown__item').filter({ hasText: 'number' });
    await numberOption.click();
    await contentPage.waitForTimeout(300);
    const numberInput = variablePage.locator('.left .el-input-number input');
    await numberInput.fill('123');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('testNumber');
    await expect(variableTable).toContainText('123');
    await expect(variableTable).toContainText('number');
  });

  test('新增boolean类型变量成功', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('testBoolean');
    const typeSelect = variablePage.locator('.left .el-select');
    await typeSelect.click();
    const booleanOption = contentPage.locator('.el-select-dropdown__item').filter({ hasText: 'boolean' });
    await booleanOption.click();
    await contentPage.waitForTimeout(300);
    const trueRadio = variablePage.locator('.left .el-radio').filter({ hasText: 'true' });
    await trueRadio.click();
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('testBoolean');
    await expect(variableTable).toContainText('true');
    await expect(variableTable).toContainText('boolean');
  });

  test('新增重复变量名显示错误提示', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('duplicateVar');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('first value');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    await nameInput.fill('duplicateVar');
    await valueTextarea.fill('second value');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const errorMessage = contentPage.locator('.el-message--error');
    await expect(errorMessage).toBeVisible({ timeout: 3000 });
  });

  test('删除变量成功,变量从列表中移除', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('toBeDeleted');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('delete me');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('toBeDeleted');
    const deleteBtn = variablePage.locator('.right .el-table .el-button').filter({ hasText: /删除|Delete/ });
    await deleteBtn.click();
    const confirmBtn = contentPage.locator('.el-message-box .el-button--primary');
    await confirmBtn.click();
    await contentPage.waitForTimeout(500);
    await expect(variableTable).not.toContainText('toBeDeleted');
  });

  test('编辑变量成功,变量值更新', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('toBeEdited');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('original value');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const editBtn = variablePage.locator('.right .el-table .el-button').filter({ hasText: /编辑|Edit/ });
    await editBtn.click();
    await contentPage.waitForTimeout(300);
    const editDialog = contentPage.locator('.el-dialog').filter({ hasText: /编辑变量|Edit Variable/ });
    await expect(editDialog).toBeVisible({ timeout: 5000 });
    const editValueTextarea = editDialog.locator('textarea');
    await editValueTextarea.fill('updated value');
    const confirmBtn = editDialog.locator('.el-button--primary');
    await confirmBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('updated value');
  });

  test('在请求Body中使用变量,发送请求后变量被正确替换', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('testVar');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('variable_value');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const addFileBtn = contentPage.locator('.pin-wrap .item').filter({ hasText: /新增文件|Add File/ }).first();
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新增接口|新建接口|Add/ });
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('测试接口');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('.url-input input');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const methodSelect = contentPage.locator('.method-select');
    await methodSelect.click();
    const postOption = contentPage.locator('.el-select-dropdown__item').filter({ hasText: 'POST' });
    await postOption.click();
    const bodyTab = contentPage.locator('[data-testid="http-params-tab-body"]');
    await bodyTab.click();
    await contentPage.waitForTimeout(300);
    const jsonRadio = contentPage.locator('.el-radio').filter({ hasText: 'json' });
    await jsonRadio.click();
    await contentPage.waitForTimeout(300);
    const monacoEditor = contentPage.locator('.s-code-editor').first();
    await monacoEditor.click();
    await contentPage.keyboard.press('Control+a');
    await contentPage.keyboard.type('{"value": "{{testVar}}"}');
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('.send-btn');
    await sendBtn.click();
    await contentPage.waitForTimeout(2000);
    const responseBody = contentPage.locator('.response-body');
    await expect(responseBody).toContainText('variable_value', { timeout: 10000 });
  });

  test('在请求URL中使用变量,发送请求后变量被正确替换', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('baseUrl');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}`);
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const addFileBtn = contentPage.locator('.pin-wrap .item').filter({ hasText: /新增文件|Add File/ }).first();
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新增接口|新建接口|Add/ });
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('URL变量测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('.url-input input');
    await urlInput.fill('{{baseUrl}}/echo');
    const sendBtn = contentPage.locator('.send-btn');
    await sendBtn.click();
    await contentPage.waitForTimeout(2000);
    const responseBody = contentPage.locator('.response-body');
    await expect(responseBody).toContainText('/echo', { timeout: 10000 });
  });

  test('在请求Headers中使用变量,发送请求后变量被正确替换', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('authToken');
    const valueTextarea = variablePage.locator('.left textarea');
    await valueTextarea.fill('Bearer test-token-123');
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const addFileBtn = contentPage.locator('.pin-wrap .item').filter({ hasText: /新增文件|Add File/ }).first();
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新增接口|新建接口|Add/ });
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('Headers变量测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('.url-input input');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const headersTab = contentPage.locator('[data-testid="http-params-tab-headers"]');
    await headersTab.click();
    await contentPage.waitForTimeout(300);
    const keyInput = contentPage.locator('.params-tree-table .rich-input').first();
    await keyInput.click();
    await contentPage.keyboard.type('Authorization');
    const valueInput = contentPage.locator('.params-tree-table .rich-input').nth(1);
    await valueInput.click();
    await contentPage.keyboard.type('{{authToken}}');
    const sendBtn = contentPage.locator('.send-btn');
    await sendBtn.click();
    await contentPage.waitForTimeout(2000);
    const responseBody = contentPage.locator('.response-body');
    await expect(responseBody).toContainText('Bearer test-token-123', { timeout: 10000 });
  });
  test('新增any类型变量执行JavaScript表达式,动态时间戳', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const moreBtn = contentPage.locator('[data-testid="banner-tool-more-btn"]');
    await moreBtn.click();
    const variableOption = contentPage.locator('.dropdown-item').filter({ hasText: /全局变量|变量/ });
    await variableOption.click();
    await contentPage.waitForTimeout(500);
    const variablePage = contentPage.locator('.s-variable');
    await expect(variablePage).toBeVisible({ timeout: 5000 });
    const nameInput = variablePage.locator('.left input').first();
    await nameInput.fill('timestamp');
    const typeSelect = variablePage.locator('.left .el-select');
    await typeSelect.click();
    const anyOption = contentPage.locator('.el-select-dropdown__item').filter({ hasText: 'any' });
    await anyOption.click();
    await contentPage.waitForTimeout(300);
    const monacoEditor = variablePage.locator('.left .monaco-editor');
    await monacoEditor.click();
    await contentPage.keyboard.press('Control+a');
    await contentPage.keyboard.type('Date.now()');
    await contentPage.waitForTimeout(300);
    const addBtn = variablePage.locator('.left .el-button--primary');
    await addBtn.click();
    await contentPage.waitForTimeout(500);
    const variableTable = variablePage.locator('.right .el-table');
    await expect(variableTable).toContainText('timestamp');
    await expect(variableTable).toContainText('any');
  });
  test('使用不存在的变量时保留原始文本', async ({ topBarPage, contentPage, clearCache, createProject }) => {
    await clearCache();
    await createProject();
    await contentPage.waitForURL(/.*#\/v1\/apidoc\/doc-edit.*/, { timeout: 5000 });
    const addFileBtn = contentPage.locator('.pin-wrap .item').filter({ hasText: /新增文件|Add File/ }).first();
    await addFileBtn.click();
    const addFileDialog = contentPage.locator('.el-dialog').filter({ hasText: /新增接口|新建接口|Add/ });
    await expect(addFileDialog).toBeVisible({ timeout: 5000 });
    const fileNameInput = addFileDialog.locator('input').first();
    await fileNameInput.fill('不存在变量测试');
    const confirmAddBtn = addFileDialog.locator('.el-button--primary').last();
    await confirmAddBtn.click();
    await contentPage.waitForTimeout(500);
    const urlInput = contentPage.locator('.url-input input');
    await urlInput.fill(`http://127.0.0.1:${MOCK_SERVER_PORT}/echo`);
    const methodSelect = contentPage.locator('.method-select');
    await methodSelect.click();
    const postOption = contentPage.locator('.el-select-dropdown__item').filter({ hasText: 'POST' });
    await postOption.click();
    const bodyTab = contentPage.locator('[data-testid="http-params-tab-body"]');
    await bodyTab.click();
    await contentPage.waitForTimeout(300);
    const jsonRadio = contentPage.locator('.el-radio').filter({ hasText: 'json' });
    await jsonRadio.click();
    await contentPage.waitForTimeout(300);
    const monacoEditor = contentPage.locator('.s-code-editor').first();
    await monacoEditor.click();
    await contentPage.keyboard.press('Control+a');
    await contentPage.keyboard.type('{"value": "{{notExistVar}}"}');
    await contentPage.waitForTimeout(300);
    const sendBtn = contentPage.locator('.send-btn');
    await sendBtn.click();
    await contentPage.waitForTimeout(2000);
    const responseBody = contentPage.locator('.response-body');
    await expect(responseBody).toContainText('{{notExistVar}}', { timeout: 10000 });
  });
});
