// 原子功能（atomicFunc）里的一条用例
export interface AtomicFunc {
  purpose: string;
  precondition: { id: string; name: string }[];
  operationSteps: { id: string; name: string }[];
  expectedResults: { id: string; name: string }[];
  checkpoints: { id: string; name: string }[];
  notes: { id: string; name: string }[];
}

// 通用树节点
export interface ModelNode {
  modelName: string;
  description: string;
  children?: ModelNode[];
  atomicFunc?: AtomicFunc[];
}

// 整个模块的入口类型
export type TestCase = ModelNode[];

export const testCase: TestCase = [
  {
    modelName: 'httpNode',
    description: 'http请求节点',
    children: [],
  },
  {
    modelName: 'websocketNode',
    description: 'websocket请求节点',
    children: [],
  },
  {
    modelName: 'httpMockNode',
    description: 'http mock节点',
    children: [],
  },
  {
    modelName: 'websocketMockNode',
    description: 'websocket mock节点',
    children: [],
  },
  {
    modelName: 'projectManager',
    description: '项目管理器',
    children: [],
  },
  {
    modelName: 'appWorkbench',
    description: '应用工作区',
    children: [
      {
        modelName: 'logo',
        description: 'logo',
        children: [],
      },
      {
        modelName: 'home',
        description: '首页',
        children: [],
      },
      {
        modelName: 'nav',
        description: '导航',
        children: [],
      },
      {
        modelName: 'addProjectToggle',
        description: '添加项目开关',
        children: [],
      },
      {
        modelName: 'aiToggle',
        description: 'AI助手开关',
        children: [],
      },
      {
        modelName: 'refresh',
        description: '刷新',
        children: [],
      },
      {
        modelName: 'maximize',
        description: '最大化',
        children: [],
      },
      {
        modelName: 'minimize',
        description: '最小化',
        children: [],
      },
      {
        modelName: 'settingsToggle',
        description: '设置开关',
        children: [],
      },
      {
        modelName: 'networkToggle',
        description: '网络开关',
        children: [],
      },
      {
        modelName: 'languageToggle',
        description: '语言切换开关',
        children: [],
      },
    ],
  },
  {
    modelName: 'projectAddon',
    description: '项目辅助功能',
    children: [
      {
        modelName: 'import',
        description: '导入项目',
        children: [],
      },
      {
        modelName: 'export',
        description: '导出项目',
        children: [],
      },
      {
        modelName: 'variable',
        description: '变量管理',
        children: [],
      },
      {
        modelName: 'commonHeader',
        description: '公共请求头',
        children: [],
      },
      {
        modelName: 'trash',
        description: '接口回收站',
        children: [],
      },
      {
        modelName: 'cookieManagement',
        description: 'cookie管理',
        children: [],
      },
    ],
  },
  {
    modelName: 'projectWorkbench',
    description: '项目工作区',
    children: [
      {
        modelName: 'banner',
        description: '项目工作区banner导航',
        children: [
          {
            modelName: 'search',
            description: '搜索',
            atomicFunc: [
              {
                purpose: '搜索框默认UI样式验证，placeholder内容、筛选图标、focus后边框高亮、输入内容后出现清空按钮',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '搜索框默认UI样式验证，placeholder内容、筛选图标、focus后边框高亮',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '搜索框输入内容后，可以匹配接口的url和名称，需要验证搜索算法对不对',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '搜索框输入内容后，若无搜索结果，需要正确展示无搜索结果提示',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '搜索框输入内容后,如果存在节点名称匹配，需要在节点名称中高亮关键字，如果存在节点url匹配，需要在url中高亮关键字,匹配中的节点如果存在父元素，则递归展示所有父元素',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '离线模式不展示高级筛选',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
            ],
          },
          {
            modelName: 'projectToggle',
            description: '项目切换',
            atomicFunc: [
              {
                purpose: '点击切换项目图标，弹出项目切换面板，点击项目名称可以切换项目，切换项目后顶部header区域需要添加一个切换项目的tab',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
            ],
          },
          {
            modelName: 'tools',
            description: '工具栏',
            atomicFunc: [
              {
                purpose: '工具栏默认按顺序展示：新增目录、新增httpNode、刷新、折叠全部、回收站、导入文档、变量图标、更多操作',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '工具栏图标可以自由拖拽交换顺序，刷新页面后顺序保持不变',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击更多操作按钮展示更多操作，显示完整的工具列表，工具列表可以自由拖拽交换顺序，刷新页面后顺序保持不变',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '更多操作中的工具列表可以固定，点击固定后展示在工具栏，点击取消固定后从工具栏移除',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '更多操作面板打开时候，点击关闭或者空白区域可以关闭面板',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击新增目录按钮，弹出目录新增面板，可以新增目录，新增目录后，新增目录面板关闭，新增目录展示在节点树中,位置排序在根目录下最后一个目录节点下方',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击新增接口按钮，弹出接口新增面板，可以新增接口，新增接口后，新增接口面板关闭，新增接口展示在节点树中,位置排序在根接最下方(需要在httpNode、websocketNode、httpMockNode、websocketMock下)',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击刷新按钮，刷新当前banner数据',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击回收站图标，展示回收站页面',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击导入文档图标，展示导入文档页面',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击导出文档图标，展示导出文档页面',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击Cookie图标，展示Cookie页面',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击变量图标，展示变量页面',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
            ],
          },
          {
            modelName: 'nodeTree',
            description: '节点树',
            children: [
              {
                modelName: 'addNode',
                description: '添加节点',
                children: [
                  {
                    modelName: '新增httpNode',
                    description: '新增http节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域添加http节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域添加http节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加http节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加http节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加http节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加http节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: 'websocketNode',
                    description: 'websocket节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域添加websocket节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域添加websocket节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加websocket节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加websocket节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加websocket节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加websocket节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: 'httpMockNode',
                    description: 'http mock节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域添加httpMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域添加httpMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加httpMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加httpMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加httpMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加httpMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: 'websocketMockNode',
                    description: 'websocket mock节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域添加websocketMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域添加websocketMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加websocketMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加websocketMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加websocketMock节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加websocketMock节点(AI)',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: 'folderNode',
                    description: 'folder节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域添加folder节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键目录添加folder节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '在folder节点上，点击新增按钮添加folder节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击新增按钮添加folder节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '边界情况测试',
                    description: '边界情况测试',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键非folder节点不出现新建接口选项',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '非folder节点点击更多按钮不出现新建接口选项',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                ],
              },
              {
                modelName: 'deleteNode',
                description: '删除节点',
                children: [
                  {
                    modelName: '删除httpNode',
                    description: '删除httpNode节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键httpNode节点删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标移动到httpNode节点，点击更多操作删除节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '按住ctrl鼠标左键批量选择httpNode节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '删除websocketNode',
                    description: '删除websocketNode节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键websocketNode节点删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标移动到websocketNode节点，点击更多操作删除节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '按住ctrl鼠标左键批量选择websocketNode节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '删除httpMockNode',
                    description: '删除httpMockNode节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键httpMockNode节点删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标移动到httpMockNode节点，点击更多操作删除节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '按住ctrl鼠标左键批量选择httpMockNode节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '删除websocketMockNode',
                    description: '删除websocketMockNode节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键websocketMockNode节点删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标移动到websocketMockNode节点，点击更多操作删除节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '按住ctrl鼠标左键批量选择websocketMockNode节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '删除folder',
                    description: '删除folder节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键folder节点删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标移动到folder节点，点击更多操作删除节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '按住ctrl鼠标左键批量选择folder节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '删除混合节点',
                    description: '删除混合节点',
                    atomicFunc: [
                      {
                        purpose: '按住ctrl鼠标左键批量选择httpNode、websocketNode、httpMockNode、websocketMockNode、folder节点，鼠标右键批量删除',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                ],
              },
              {
                modelName: '重命名节点',
                description: '重命名节点',
                children: [
                  {
                    modelName: '重命名节点httpNode节点',
                    description: '重命名节点httpNode节点',
                    atomicFunc: [
                      {
                        purpose: 'active 节点，点击节点右键，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: 'active 节点，F2重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击节点更多操作，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '节点名称未填写不允许重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '重命名节点websocketNode节点',
                    description: '重命名节点websocketNode节点',
                    atomicFunc: [
                      {
                        purpose: 'active 节点，点击节点右键，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: 'active 节点，F2重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击节点更多操作，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '节点名称未填写不允许重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '重命名节点httpMockNode节点',
                    description: '重命名节点httpMockNode节点',
                    atomicFunc: [
                      {
                        purpose: 'active 节点，点击节点右键，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: 'active 节点，F2重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击节点更多操作，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '节点名称未填写不允许重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '重命名节点websocketMock节点',
                    description: '重命名节点websocketMock节点',
                    atomicFunc: [
                      {
                        purpose: 'active 节点，点击节点右键，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: 'active 节点，F2重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击节点更多操作，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '节点名称未填写不允许重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '重命名节点folder节点',
                    description: '重命名节点folder节点',
                    atomicFunc: [
                      {
                        purpose: 'active 节点，点击节点右键，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: 'active 节点，F2重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '点击节点更多操作，点击重命名，输入名称，回车或blur',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '节点名称未填写不允许重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                ],
              },
              {
                modelName: '鼠标右键',
                description: '鼠标右键',
                children: [
                  {
                    modelName: '鼠标右键空白区域',
                    description: '鼠标右键空白区域',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键空白区域，出现新建接口、新建文件夹、设置公共请求头、粘贴节点(可能置灰)等功能',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域，点击新建接口(httpNode、websocketNode、httpMockNode、websocketMockNode)、成功后在根节点末尾生成节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域，点击新建文件夹、成功后在根节点最后一个目录节点下面生成目录节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域，点击设置公共请求头，导航区域增加公共请求头标签、内容区域出现公共请求头设置内容',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键空白区域，点击粘贴，可以粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '鼠标右键folder节点',
                    description: '鼠标右键folder节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键folder节点，出现新建接口、新建文件夹、设置公共请求头、剪切、复制、粘贴(可能置灰)、重命名、删除等功能',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击新建接口(httpNode、websocketNode、httpMockNode、websocketMockNode)、成功后在当前folder内生成节点，并且生成的节点排在末尾',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击新建文件夹、成功后在当前folder内生成节点，生成的节点在当前节点最后一个folder节点下面',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击设置公共请求头，导航区域增加公共请求头标签，标签文案正确、内容区域出现公共请求头设置内容',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击剪切，被剪切节点样式发生改变，点击粘贴(空白区域、folder节点上)，可以粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击复制，点击粘贴(空白区域、folder节点上)，可以粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击粘贴，可以按照逻辑(情况一：单个httpNode、websocketNode、httpMockNode、websocketMockNode。情况二:单个folder。情况三：多个非folder节点。情况四：多个纯folder节点。情况五：混合类型节点)粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击重命名(或f2)，可以正常重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键folder节点，点击删除(或delete)，可以正常删除目录',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                  {
                    modelName: '鼠标右键非folder节点',
                    description: '鼠标右键非folder节点',
                    atomicFunc: [
                      {
                        purpose: '鼠标右键非folder节点，出现剪切、复制、生成副本、重命名、删除等功能',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键非folder节点，点击剪切，被剪切节点样式发生改变，点击粘贴(空白区域、folder节点上)，可以粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键非folder节点，点击复制，点击粘贴(空白区域、folder节点上)，可以粘贴节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键非folder节点，点击生成副本，可以在当前节点后面生成副本节点',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键非folder节点，点击重命名(或f2)，可以正常重命名',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                      {
                        purpose: '鼠标右键非folder节点，点击删除(或delete)，可以正常删除目录',
                        precondition: [],
                        operationSteps: [],
                        expectedResults: [],
                        checkpoints: [],
                        notes: [],
                      },
                    ],
                  },
                ],
              },
              {
                modelName: '节点树其他情况',
                description: '节点树其他情况',
                atomicFunc: [
                  {
                    purpose: '在根节点新增、粘贴非folder节点，会排序在末尾',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '在根节点新增、粘贴folder节点，会排序到根目录下最后一个目录节点下面',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '在根节点粘贴包含folder节点的混合节点，folder节点会排序到根目录下最后一个目录节点下面，非folder节点会排序在末尾',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                ],
              },
            ],
          },
          {
            modelName: 'banner区域其他功能',
            description: 'banner区域其他功能',
            atomicFunc: [
              {
                purpose: '可左右拖拽banner，需要判断最大和最小宽度，双击需要还原为默认样式',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: 'httpMockNode启动后，banner节点需要有呼吸小圆点效果',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
            ],
          },
        ],
      },
      {
        modelName: 'nav',
        description: '工作区导航',
        children: [
          {
            modelName: '项目工作区导航基本样式',
            description: '项目工作区导航基本样式',
            children: [],
          },
          {
            modelName: 'banner与项目工作区导航交互',
            description: 'banner与项目工作区导航交互',
            atomicFunc: [
              {
                purpose: '单击左侧非folder类型节点，右侧导航栏会新增一个tab页签，并且页签为非固定状态，页签中字体为斜体',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '双击左侧非folder类型节点，右侧导航栏会新增一个tab页签，并且页签为固定状态，页签中字体正常展示',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '单击左侧folder类型节点，右侧导航栏不会新增一个tab页签',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '单击左侧非folder类型节点A，再点击左侧folder类型节点B，节点B的tab会覆盖节点A的tab',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: 'tab页签存在固定页签和非固定页签，当前选中页签可以是固定也可以是非固定的，单击左侧非folder类型节点，会选中并覆盖未固定页签，并且也是未固定的',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: 'tab页签存在固定页签和非固定页签，当前选中页签可以是固定也可以是非固定的，双击左侧非folder类型节点，会选中并覆盖未固定页签，并且是固定的',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: 'banner新增一个节点会在右侧导航栏新增一个tab页签，页签位置在当前激活页签右侧',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '删除banner节点，右侧导航栏删除对应tab页签',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '重命名banner节点，右侧导航栏对应tab页签字体更新',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
              {
                purpose: '点击tab页签，左侧banner节点高亮，若无节点相关tab页签被选中，则取消banner高亮',
                precondition: [],
                operationSteps: [],
                expectedResults: [],
                checkpoints: [],
                notes: [],
              },
            ],
          },
          {
            modelName: 'tab操作',
            description: 'tab操作',
            children: [],
          },
          {
            modelName: 'tab拖拽',
            description: 'tab拖拽',
            children: [],
          },
        ],
      },
      {
        modelName: 'httpNode工作区',
        description: 'httpNode工作区',
        children: [
          {
            modelName: 'operation',
            description: '操作区域',
            children: [
              {
                modelName: '请求方法录入区域',
                description: '请求方法录入区域',
                atomicFunc: [
                  {
                    purpose: '正确展示GET, POST, PUT, DEL, PATCH, HEAD, OPTIONS,选择或者点击空白区域下拉菜单消失',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '切换请求方法不会改变banner节点中的请求方法、也不会改变nav栏节点中的请求方法，只有保存后才会生效',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '切换所有请求方法，点击发送请求，调用测试服务器/echo接口，返回method为选中的method',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                ],
              },
              {
                modelName: '请求url录入区域',
                description: '请求url录入区域',
                atomicFunc: [
                  {
                    purpose: '输入http://localhost:{环境变量中的端口}/echo,点击发送请求，调用测试服务器/echo接口，成功返回',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '输入http://127.0.0.1:{环境变量中的端口}/echo,点击发送请求，调用测试服务器/echo接口，成功返回',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '定义一个localUrl变量，输入http://{{ localUrl }}:{环境变量中的端口}/echo,点击发送请求，调用测试服务器/echo接口，成功返回',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '输入127.0.0.1:{环境变量中的端口}/echo(没有协议自动添加http), 点击发送请求，调用测试服务器/echo接口，成功返回',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '输入127.0.0.1:{环境变量中的端口}/echo?id=3&name=lee, blur后，url结果为http://127.0.0.1:{环境变量中的端口}/echo，id和name会出现在query参数中',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '输入127.0.0.1:{环境变量中的端口}/echo?id=3&name=lee, blur后，url结果为http://127.0.0.1:{环境变量中的端口}/echo，id和name会出现在query参数中，点击发送请求，返回结果中url和query参数正确',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                  {
                    purpose: '输入127.0.0.1:{环境变量中的端口}/echo/{userId}/posts/{postId}，userId和postId会出现在query参数中，点击发送请求，返回结果中url和path参数正确',
                    precondition: [],
                    operationSteps: [],
                    expectedResults: [],
                    checkpoints: [],
                    notes: [],
                  },
                ],
              },
              {
                modelName: '请求url展示区域',
                description: '请求url展示区域',
                children: [],
              },
              {
                modelName: '请求操作区域',
                description: '请求操作区域',
                children: [],
              },
            ],
          },
          {
            modelName: 'inputArea',
            description: '录入区域',
            children: [
              {
                modelName: 'query',
                description: 'Query参数',
                children: [],
              },
              {
                modelName: 'body',
                description: '请求体',
                children: [],
              },
              {
                modelName: 'header',
                description: '请求头',
                children: [],
              },
              {
                modelName: 'preScript',
                description: '前置脚本',
                children: [],
              },
              {
                modelName: 'afterScript',
                description: '后置脚本',
                children: [],
              },
              {
                modelName: 'remark',
                description: '备注',
                children: [],
              },
            ],
          },
          {
            modelName: 'settings',
            description: '设置',
            children: [
              {
                modelName: 'responseInfo',
                description: '返回信息',
                children: [
                  {
                    modelName: 'responseValue',
                    description: '返回值',
                    children: [],
                  },
                  {
                    modelName: 'responseHeader',
                    description: '返回头',
                    children: [],
                  },
                  {
                    modelName: 'responseCookie',
                    description: '返回cookie',
                    children: [],
                  },
                  {
                    modelName: 'rawValue',
                    description: '原始值',
                    children: [],
                  },
                ],
              },
              {
                modelName: 'basicInfo',
                description: '基础信息',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
